# Generated by Django 3.2.2 on 2021-05-06 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_index_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('investor_id', models.AutoField(primary_key=True, serialize=False)),
                ('worth', models.FloatField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('asset_name', models.CharField(max_length=200)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_index_app.investor')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
