# Generated by Django 3.2.2 on 2021-05-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_index_app', '0002_auto_20210506_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transacciones',
            new_name='Transactions',
        ),
    ]
