# Generated by Django 3.2.2 on 2021-05-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_index_app', '0003_rename_transacciones_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(),
        ),
    ]
