# Generated by Django 3.1.2 on 2021-05-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_inversiones', '0002_auto_20210505_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='moneda',
            field=models.CharField(default='EUR', max_length=3),
            preserve_default=False,
        ),
    ]
