# Generated by Django 3.1.2 on 2021-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_inversiones', '0003_transacciones_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='simbolo',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
