# Generated by Django 3.1.2 on 2021-05-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_inversiones', '0004_transacciones_simbolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='bolsa',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
